import { GlobalVariables } from '../../core/models/globalvariables';

export class EdiHbl {
    hbl_pkid: string;
    hbl_header_id: string;
    hbl_sender: string;
    hbl_message_date: string;
    hbl_message_file_name: string;
    hbl_message_number: string;

    hbl_status: string;
    hbl_updated: string;
    hbl_pol_agent: string;


    hbl_carrier_name: string;
    hbl_agent_name: string;
    hbl_master_no: string;
    hbl_master_date: string;
    hbl_direct_bl: string;
    hbl_house_no: string;
    hbl_house_date: string;
    hbl_ams_no: string;
    hbl_isf_no: string;
    hbl_por_code: string;
    hbl_por_name: string;
    hbl_pol_code: string;
    hbl_pol_name: string;
    hbl_pod_code: string;
    hbl_pod_name: string;
    hbl_pofd_code: string;
    hbl_pofd_name: string;
    hbl_delivery_code: string;
    hbl_delivery_name: string;
    hbl_etd: string;
    hbl_eta: string;
    hbl_etd_confirm: string;
    hbl_delivery_date: string;
    hbl_mode: string;
    hbl_movement: string;
    hbl_service_type: string;
    hbl_payment_type: string;
    hbl_freight: string;
    hbl_book_no: string;
    hbl_contract_no: string;
    hbl_ref_no: string;
    hbl_branch: string;
    hbl_issu_place: string;
    hbl_issu_date: string;
    hbl_is_ddu: string;
    hbl_is_ddp: string;
    hbl_is_exwork: string;
    hbl_remark: string;
    hbl_shipper_name: string;
    hbl_shipper_add1: string;
    hbl_shipper_add2: string;
    hbl_shipper_add3: string;
    hbl_shipper_add4: string;
    hbl_shipper_add5: string;
    hbl_shipper_contact: string;
    hbl_shipper_tel: string;
    hbl_shipper_email: string;
    hbl_consignee_name: string;
    hbl_consignee_add1: string;
    hbl_consignee_add2: string;
    hbl_consignee_add3: string;
    hbl_consignee_add4: string;
    hbl_consignee_add5: string;
    hbl_consignee_contact: string;
    hbl_consignee_tel: string;
    hbl_consignee_email: string;
    hbl_notify_name: string;
    hbl_notify_add1: string;
    hbl_notify_add2: string;
    hbl_notify_add3: string;
    hbl_notify_add4: string;
    hbl_notify_add5: string;
    hbl_notify_contact: string;
    hbl_notify_tel: string;
    hbl_notify_email: string;
    hbl_vessel: string;
    hbl_voyage: string;
    hbl_mother_vessel: string;
    hbl_mother_voyage: string;
    hbl_selected : boolean;


    //   ord_parent_id : string;
    //   ord_exp_id : string;
    //   ord_exp_name : string;
    //   ord_imp_id : string;
    //   ord_imp_name : string;
    //   ord_invno : string;
    //   ord_uneco : string;
    //   ord_po : string;
    //   ord_style : string;
    //   ord_cbm : number;
    //   ord_pcs : number;
    //   ord_pkg : number;
    //   ord_grwt : number;
    //   ord_ntwt : number;
    //   ord_hs_code : string;
    //   ord_cargo_status : string;
    //   ord_desc : string;
    //   ord_color : string;
    //   ord_stylename : string;
    //   ord_contractno : string;
    //   ord_exp_code : string;
    //   ord_imp_code : string;
    //   job_docno : string;
    //   ord_agent_id : string;
    //   ord_agent_name : string;
    //   ord_agent_code : string;
    //   rec_created_dte : string;
    //   remove : string;
    //   ord_source : string;
    //   ord_selected : boolean;
    //   ord_booking_id : string;
    //   ord_approved : boolean;
    //   ord_booking_no : string;
    //   ord_booking_date : string;
    //   ord_rnd_insp_date : string;
    //   ord_po_rel_date : string;
    //   ord_cargo_ready_date : string;
    //   ord_fcr_date : string;
    //   ord_insp_date : string;
    //   ord_stuf_date : string;
    //   ord_whd_date : string;
    //   ord_track_status : string;
    //   ord_ourbooking_no : string;
    //   ord_week_no : number;
    //   ord_delvi_date : string;
    //   ord_dlv_pol_date : string;
    //   ord_dlv_pod_date : string;
    //   ord_uid_orgin : string;
    //   ord_uid : number;
    //   ord_status_color : string;

    //   ord_pol : string;
    //   ord_pod : string;
    //   ord_pol_id : string;
    //   ord_pod_id : string;
    //   ord_pol_code : string;
    //   ord_pod_code : string;

    //   ord_agentref_id : string;
    //   ord_ftp_status : string;
    //   ord_boarding1 : string;
    //   ord_boarding2 : string;
    //   ord_instock1 : string;
    //   ord_instock2 : string;

    //   transfer_remarks : string;

    rec_mode: string;
    rec_category: string;

    rec_deleted: boolean;

    _globalvariables: GlobalVariables;
}

